### ISSUE TITLE
Rclone authentication

### ISSUE THREAD

**Issue by camjac251** [l3uddz/plex_autoscan#28] opened 2018-04-21 18:23 UTC
Would it be possible to be able to connect to rclone's rc with a password? I am running this on a box with many users and anyone could find the port I use and run their own commands since it is open locally without authorization.

`–rc-htpasswd=file.hpasswd` or `--rc-user=VALUE` 
` --rc-pass=VALUE` would be the commands I'd use to add authentication to rclone's rc

**Comment by l3uddz** [comment] 2018-04-21 19:07
It should already support authentication, just prefix your URL with user:password, e.g. 

```http://username:password@localhost:5572```

**Comment by camjac251** [comment] 2018-04-21 19:13
Oh I didn't think of that, thank you for the fast reply.

**Comment by l3uddz** [comment] 2018-04-21 19:29
np, pls report back if it works and close the issue 😀

**Comment by camjac251** [comment] 2018-04-21 21:13
I don't think the script is working for me. Not sure what is wrong on this. I am using rclone with google drive and cache/crypt. All works great. Cache however stays up for 60 minutes before syncing to Gdrive. 

```bash
 2018-04-21 14:32:38,807 -     INFO -  AUTOSCAN [140338646009600]: Client '127.0.0.1' made a test request, event: 'Test'
 2018-04-21 14:36:01,280 -    DEBUG -  AUTOSCAN [140338646009600]: Client '127.0.0.1' request dump:
{
    "episodeFile": {
        "id": 10101, 
        "path": "/home/user/files/plex/TV/TVShow.mkv", 
        "quality": "WEBDL-1080p", 
        "qualityVersion": 1, 
        "relativePath": "Season 01/TVShow.mkv", 
        "releaseGroup": "Me", 
        "sceneName": "TVShow"
    }, 
    "episodes": [
        {
            "airDate": "2018-01-23", 
            "airDateUtc": "2018-01-23T13:00:00Z", 
            "episodeNumber": 26, 
            "id": 10101, 
            "quality": "WEBDL-1080p", 
            "qualityVersion": 1, 
            "releaseGroup": "Me", 
            "sceneName": "TVShow", 
            "seasonNumber": 18, 
            "title": "Episode Title"
        }
    ], 
    "eventType": "Download", 
    "isUpgrade": false, 
    "series": {
        "id": 715, 
        "path": "/home/user/rclone-drive/TV/TVShow", 
        "title": "TVShow", 
        "tvdbId": 10101
    }
}
 2018-04-21 14:36:01,280 -     INFO -  AUTOSCAN [140338646009600]: Client '127.0.0.1' scan request for series: '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv', event: 'Download'
 2018-04-21 14:36:01,281 -    DEBUG -  AUTOSCAN [140338646009600]: Using section id: 2 for '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv'
 2018-04-21 14:36:01,282 -     INFO -      PLEX [140338423125760]: Scan request from Sonarr for '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv', sleeping for 5 seconds...
 2018-04-21 14:36:06,284 -     INFO -      PLEX [140338423125760]: File '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv' exists on check 1 of 10.
 2018-04-21 14:36:06,284 -    DEBUG -     UTILS [140338423125760]: Using priority 0 for path '/home/user/rclone-drive/TV/TVShow/Season 01'
 2018-04-21 14:36:06,285 -    DEBUG -      PLEX [140338423125760]: Waiting for turn in the scan request backlog with priority: 0
 2018-04-21 14:36:06,285 -     INFO -      PLEX [140338423125760]: Scan request is now being processed
 2018-04-21 14:36:06,300 -     INFO -      PLEX [140338423125760]: No 'Plex Media Scanner' processes were found.
 2018-04-21 14:36:06,300 -     INFO -      PLEX [140338423125760]: Starting Plex Scanner
 2018-04-21 14:36:06,300 -    DEBUG -      PLEX [140338423125760]: export LD_LIBRARY_PATH=/home/user/Library/Plex/current/usr/lib/plexmediaserver;export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/home/user/Library/Application\ Support;/home/user/Library/Plex/current/usr/lib/plexmediaserver/Plex\ Media\ Scanner --scan --refresh --section 2 --directory '/home/user/rclone-drive/TV/TVShow/Season 01'
 2018-04-21 14:36:08,059 -     INFO -     UTILS [140338423125760]: GUI: Scanning TVShow Season 01 Episode 17
 2018-04-21 14:36:08,061 -     INFO -     UTILS [140338423125760]: GUI: Scanning TVShow Season 01 Episode 26
 2018-04-21 14:36:12,545 -     INFO -      PLEX [140338423125760]: Finished scan!
 2018-04-21 14:36:12,546 -    DEBUG -      PLEX [140338423125760]: Sleeping 10 seconds before sending analyze request
 2018-04-21 14:36:22,550 -    ERROR -      PLEX [140338423125760]: Could not locate record in media_parts where file = '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv', 1/5 attempts...
 2018-04-21 14:36:32,559 -    ERROR -      PLEX [140338423125760]: Could not locate record in media_parts where file = '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv', 2/5 attempts...
 2018-04-21 14:36:42,569 -    ERROR -      PLEX [140338423125760]: Could not locate record in media_parts where file = '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv', 3/5 attempts...
 2018-04-21 14:36:52,576 -    ERROR -      PLEX [140338423125760]: Could not locate record in media_parts where file = '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv', 4/5 attempts...
 2018-04-21 14:37:02,586 -    ERROR -      PLEX [140338423125760]: Could not locate record in media_parts where file = '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv', 5/5 attempts...
 2018-04-21 14:37:12,596 -    ERROR -      PLEX [140338423125760]: Could not locate record in media_parts where file = '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv' after 5 tries...
 2018-04-21 14:37:12,597 -     INFO -      PLEX [140338423125760]: Aborting analyze of '/home/user/rclone-drive/TV/TVShow/Season 01/TVShow.mkv' because could not find any metadata_item_id for it
```


I censored the log a bit to not show any revealing data. The paths are similar to what I have setup.

**Comment by camjac251** [comment] 2018-04-21 21:15
I also noticed that LD_LIBRARY_PATH=/home/user/Library/Plex/current/usr/lib/plexmediaserver even though in my bashprofile it's set to /home/user/lib.

**Comment by l3uddz** [comment] 2018-04-21 21:29
Sounds like it's improperly configured. 

Is it a native Plex install?

**Comment by camjac251** [comment] 2018-04-21 21:36
Not quite, it's based on the whatbox plexinstaller which creates a file structure like this

/home/username/Library

- Application Support
   - Plex Media Server
     - Plug-in Support
        - Databases
- Caches
- Logs
- Plex
   - current (symlink to latest)
   - plexmediaserver-1.12.3.4973-215c28d86.x86_64
      - usr
           - lib
               - plexmediaserver
                       - Plex Media Scanner
   - plexmediaserver-1.12.3.4973-215c28d86.x86_64.rpm

**Comment by l3uddz** [comment] 2018-04-21 21:50
not quite sure what you will be wanting to use for that field, have no experience with whatbox. typically the default would be fine for normal installations though, e.g. for a docker install the LD_LIBRARY_PATH would have some of the contents:

```
➜  ~ docker exec -it plex ls -la /usr/lib/plexmediaserver
total 130212
drwxr-xr-x  4 root root    20480 Apr 13 21:03 .
drwxr-xr-x  1 root root     4096 Oct 28 16:50 ..
-rwxr-xr-x  1 root root  1461680 Mar 29 20:05 CrashUploader
-rwxr-xr-x  1 root root    10653 Mar 29 20:05 MigratePlexServerConfig.sh
-rwxr-xr-x  1 root root   297432 Mar 29 20:05 Plex Commercial Skipper
-rwxr-xr-x  1 root root  4063392 Mar 29 20:05 Plex DLNA Server
-rwxr-xr-x  1 root root  5060176 Mar 29 20:05 Plex Media Scanner
-rwxr-xr-x  1 root root 15834968 Mar 29 20:05 Plex Media Server
-rwxr-xr-x  1 root root 20684696 Mar 29 20:05 Plex Media Server Tests
-rwxr-xr-x  1 root root   886536 Mar 29 20:05 Plex Relay
-rwxr-xr-x  1 root root     5048 Mar 29 20:05 Plex Script Host
-rwxr-xr-x  1 root root 12980928 Mar 29 20:05 Plex Transcoder
-rwxr-xr-x  1 root root  5354928 Mar 29 20:05 Plex Tuner Service
drwxr-xr-x 10 root root    12288 Apr 13 21:03 Resources
drwxr-xr-x  2 root root     4096 Apr 13 21:03 dri
-rw-r--r--  1 root root    32912 Mar 29 20:05 libargtable2.so.0
-rw-r--r--  1 root root  1772872 Mar 29 20:05 libavcodec.so.57
-rw-r--r--  1 root root  3277696 Mar 29 20:05 libavformat.so.57
```

Also, it appears that some files were scanned, but not the file that it was trying to scan/aiming to scan, that is the cause of the analyze abort, if the file wasnt scanned into plex, it wont beable to find the metadata item id to use for the analyze request. 

It will probably take some trial and error before you get it setup correctly for your install.

**Comment by camjac251** [comment] 2018-05-01 00:45
I believe I got it working although have a new error. Not sure if a new issue is needed but this was the log of the error

```bash


        "id": ###,
        "path": "/home/username/rclone/TV/ShowName",
        "title": "ShowName",
        "tvdbId": #######
    }
}
 2018-04-30 18:46:52,962 -     INFO -  AUTOSCAN [139720432170752]: Client '127.0.0.1' scan request for series: '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv', event: 'Download'
 2018-04-30 18:46:52,962 -    DEBUG -  AUTOSCAN [139720432170752]: Using section id: 2 for '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv'
 2018-04-30 18:46:53,070 -     INFO -  AUTOSCAN [139720432170752]: Added '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv' to database, proceeding with scan
 2018-04-30 18:46:53,071 -     INFO -      PLEX [139720217663232]: Scan request from Sonarr for '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv', sleeping for 5 seconds...
 2018-04-30 18:46:58,646 -     INFO -      PLEX [139720217663232]: File '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv' exists on check 1 of 10.
 2018-04-30 18:46:58,647 -    DEBUG -     UTILS [139720217663232]: Using priority 0 for path '/home/username/rclone/TV/ShowName/Season #'
 2018-04-30 18:46:58,647 -    DEBUG -      PLEX [139720217663232]: Waiting for turn in the scan request backlog with priority: 0
 2018-04-30 18:46:58,647 -     INFO -      PLEX [139720217663232]: Scan request is now being processed
 2018-04-30 18:46:58,662 -     INFO -      PLEX [139720217663232]: No 'Plex Media Scanner' processes were found.
 2018-04-30 18:46:58,662 -     INFO -      PLEX [139720217663232]: Starting Plex Scanner
 2018-04-30 18:46:58,663 -    DEBUG -      PLEX [139720217663232]: export LD_LIBRARY_PATH=/home/username/Library/Plex/current/usr/lib/plexmediaserver;export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/home/username/Library/Application\ Support;/home/username/Library/Plex/current/usr/lib/plexmediaserver/Plex\ Media\ Scanner --scan --refresh --section 2 --directory '/home/username/rclone/TV/ShowName/Season #'
 2018-04-30 18:46:59,388 -     INFO -     UTILS [139720217663232]: GUI: Scanning Last Week Tonight With John Oliver Season 2018 Episode 2018-04-08
 2018-04-30 18:46:59,389 -     INFO -     UTILS [139720217663232]: GUI: Scanning Last Week Tonight With John Oliver Season # Episode 7
 2018-04-30 18:47:01,553 -     INFO -     UTILS [139720217663232]: GUI: Scanning Last Week Tonight With John Oliver Season # Episode 8
 2018-04-30 18:47:01,555 -     INFO -     UTILS [139720217663232]: GUI: Scanning Last Week Tonight With John Oliver Season # Episode 9
 2018-04-30 18:47:01,853 -     INFO -      PLEX [139720217663232]: Finished scan!
 2018-04-30 18:47:01,920 -     INFO -      PLEX [139720217663232]: Removed '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv' from database
 2018-04-30 18:47:02,922 -     INFO -      PLEX [139720217663232]: There is 0 queued items remaining...
 2018-04-30 18:47:02,922 -     INFO -      PLEX [139720217663232]: Checking deleted item count in 10 seconds...
 2018-04-30 18:47:12,959 -     INFO -      PLEX [139720217663232]: Skipping emptying trash as there were no deleted items
 2018-04-30 18:47:12,960 -    DEBUG -      PLEX [139720217663232]: Sleeping 10 seconds before sending analyze request
 2018-04-30 18:47:22,975 -    ERROR -      PLEX [139720217663232]: Could not locate record in media_parts where file = '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv', 1/5 attempts...
 2018-04-30 18:47:32,983 -    ERROR -      PLEX [139720217663232]: Could not locate record in media_parts where file = '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv', 2/5 attempts...
 2018-04-30 18:47:42,994 -    ERROR -      PLEX [139720217663232]: Could not locate record in media_parts where file = '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv', 3/5 attempts...
 2018-04-30 18:47:53,005 -    ERROR -      PLEX [139720217663232]: Could not locate record in media_parts where file = '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv', 4/5 attempts...
 2018-04-30 18:48:03,015 -    ERROR -      PLEX [139720217663232]: Could not locate record in media_parts where file = '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv', 5/5 attempts...
 2018-04-30 18:48:13,025 -    ERROR -      PLEX [139720217663232]: Could not locate record in media_parts where file = '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv' after 5 tries...
 2018-04-30 18:48:13,026 -     INFO -      PLEX [139720217663232]: Aborting analyze of '/home/username/rclone/TV/ShowName/Season #/ShowName - S#E# - WEBDL-1080p plex.mkv' because could not find any metadata_item_id for it
```

**Closed as completed** 2018-09-27 16:24 UTC
